In [1]:
%matplotlib inline
import timeit


# Analysis of DBSCAN clustering algorithm






In [2]:
print(__doc__)

import numpy as np

from sklearn.cluster import DBSCAN
#from sklearn.cluster import OPTICS
from sklearn import metrics
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import StandardScaler
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
# #############################################################################
# Generate sample data


Automatically created module for IPython interactive environment


In [3]:
from scipy.spatial import distance

In [4]:
with open("dim15.txt") as textFile:
        lines = [line.split() for line in textFile]

In [5]:
X1=np.asarray(lines)

In [6]:
X1=np.array(X1).astype(np.int)

In [7]:
print(X1)

[[     0      0      0 ...      0      0      0]
 [ 29020 860619 658827 ... 620337 310595 461270]
 [ 32683 862625 671429 ... 594499 319498 478757]
 ...
 [897758 761942 459441 ... 392910 696408 158048]
 [897880 763042 462386 ... 375089 697630 130641]
 [898164 741119 487449 ... 395196 727106 136475]]


In [8]:
X=X1

In [9]:
len(X1)

10126

In [10]:
len(X1)/2


5063.0

In [11]:
X=X1[0:675]

In [12]:
len(X)

675

In [13]:
X

array([[     0,      0,      0, ...,      0,      0,      0],
       [ 29020, 860619, 658827, ..., 620337, 310595, 461270],
       [ 32683, 862625, 671429, ..., 594499, 319498, 478757],
       ...,
       [ 70466, 845506, 642872, ..., 626937, 307388, 460100],
       [ 70477, 842786, 656535, ..., 615808, 320045, 457605],
       [ 70610, 839462, 684469, ..., 630462, 311462, 471009]])

In [14]:
#dst = distance.euclidean(a, b)

In [15]:
#dst

In [16]:
%%timeit

#A = X1
clustering = DBSCAN(eps=2500, min_samples=5, metric='euclidean').fit_predict(X, y=None, sample_weight=None)




5.77 ms ± 73.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
from sklearn.cluster import DBSCAN
import numpy as np
#A = X1
clustering = DBSCAN(eps=38000, min_samples=31, metric='euclidean').fit_predict(X, y=None, sample_weight=None)



In [18]:
#optics=OPTICS(min_samples=9, rejection_ratio=0.5)

In [19]:
np.unique(clustering)

array([-1,  0])

In [20]:
print("Silhouette Coefficient: %0.3f"% metrics.silhouette_score(X,clustering ))

Silhouette Coefficient: 0.013


In [21]:
from sklearn.metrics import davies_bouldin_score

In [22]:
print("Davis Coefficient: %0.3f"% metrics.davies_bouldin_score(X,clustering ))

Davis Coefficient: 12.778


/Users/roswal/anaconda3/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances


In [23]:
print("Harabaz Coefficient: %0.3f"% metrics.calinski_harabaz_score(X, clustering))

Harabaz Coefficient: 1.209
